// The public science notes page (app/dist/science/index.html), generated by app/build.mjs from
// design/canonical/public_provenance.json — itself generated from the ledger, the reference registry and the validation
// reports (science/tools/build_provenance.py). Nothing here is typed by hand. Equations are rendered by KaTeX at build
// time; fonts are inlined, so the page works offline beside the app. Every claim, reference and check has a stable public
// anchor (/science/#thermal-doppler-broadening); internal ids stay in data-id attributes for traceability only.
import fs from 'node:fs'; import path from 'node:path'; import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);

export const esc = s => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
/** public text: escaped, with [[#anchor|label]] turned into links (href prefix: '' on this page, 'science/index.html' from the app) */
export function rich(t, base = '') { return esc(t).replace(/\[\[#([a-z0-9-]+)\|([^\]]+)\]\]/g, (m, a, l) => `<a href="${base}#${a}">${l}</a>`); }

export function sciencePage(prov, { fontsCSS, katexCSS, version, repository = null }) {
  const repo = t => repository ? `<a href="${repository}">${t}</a>` : t;   // the public repository, once it exists (release.json)
  const katex = require('./vendor/katex/katex.min.js'), { site, beats, entries, references: R, validations: V } = prov;
  const tex = (s, display = true) => katex.renderToString(s, { throwOnError: true, displayMode: display, output: 'htmlAndMathml' });
  const byAnchor = Object.fromEntries(Object.values(R).map(r => [r.anchor, r]));
  const vBy = Object.fromEntries(Object.entries(V).map(([id, v]) => [id, v]));
  const refLinks = r => r.links.map(l => l.href ? `<a href="${esc(l.href)}" rel="noopener">${esc(l.label)}</a>` : `<span>${esc(l.label)}</span>`).join(' · ');
  const scene = n => `<a href="../lya.html#beat=${n}">${n} · ${esc(beats[String(n)].title)}</a>`;
  const BASIS = { identity: 'a mathematical identity, following from the claims it builds on', calculation: 'a calculation from the cited inputs', script: 'produced by a deterministic script in this repository', numerical: 'checked numerically against an independent code', constants: 'constants typed independently and compared', 'sign test': 'a sign test', test: 'a convention of this resource, checked by an automated test', model: 'an idealised model chosen by this resource and declared here', analytic: 'compared with an analytic result' };
  const entryCard = ([id, e]) => {
    const srcs = e.sources.length ? `<dl class="kv"><dt>Sources</dt><dd><ul>${e.sources.map(x => { const r = R[x.ref]; return `<li><a href="#${r.anchor}">${esc(r.short)}</a>${x.location ? ` — <span class="loc">${esc(x.location)}</span>` : ''}${x.role === 'secondary' ? ' <span class="muted">(secondary)</span>' : ''}</li>`; }).join('')}</ul></dd></dl>`
      : `<dl class="kv"><dt>Sources</dt><dd>${e.representation ? 'A teaching representation chosen by this resource — described here so it is not mistaken for physics.' : `No literature source: ${esc(BASIS[e.basis] || 'see the check below')}.`}</dd></dl>`;
    const checks = e.check || e.validations.length ? `<dl class="kv"><dt>How it is checked</dt><dd>${e.check ? `<p>${rich(e.check)}</p>` : ''}${e.validations.map(v => `<p><a href="#${vBy[v].anchor}">${esc(vBy[v].name)}</a> — <span class="status ${vBy[v].status.startsWith('pass') ? 'ok' : 'bad'}">${esc(vBy[v].status)}</span></p>`).join('')}</dd></dl>` : '';
    return `<article class="entry" id="${e.anchor}" data-id="${id}">
<h4><a class="self" href="#${e.anchor}" aria-label="link to this claim">¶</a> ${esc(e.title)}</h4>
<p class="claim">${rich(e.claim)}</p>
${e.equations.map(q => `<div class="eq">${tex(q.tex)}${q.meaning ? `<p class="muted">${rich(q.meaning)}</p>` : ''}</div>`).join('')}
${e.convention ? `<dl class="kv"><dt>Convention</dt><dd>${rich(e.convention)}</dd></dl>` : ''}
${e.assumptions.length ? `<dl class="kv"><dt>Assumptions</dt><dd><ul>${e.assumptions.map(a => `<li>${rich(a)}</li>`).join('')}</ul></dd></dl>` : ''}
${e.validity ? `<dl class="kv"><dt>Valid for</dt><dd>${rich(e.validity)}</dd></dl>` : ''}
${e.simplifications.length ? `<dl class="kv"><dt>Simplifications</dt><dd><ul>${e.simplifications.map(a => `<li>${rich(a)}</li>`).join('')}</ul></dd></dl>` : ''}
${srcs}${checks}
<p class="meta">${e.beats.length ? `used in ${e.beats.map(scene).join(', ')} · ` : 'not used by a scene · '}status: ${esc(e.status)} · id ${esc(id)}</p>
</article>`;
  };
  const linked = new Set(Object.values(entries).filter(e => e.used).flatMap(e => [...JSON.stringify(e).matchAll(/\[\[#([a-z0-9-]+)\|/g)].map(m => m[1])));
  const used = Object.entries(entries).filter(([, e]) => e.used || linked.has(e.anchor));   // the claims the scenes rely on, and those they cite
  const valRows = Object.entries(V).map(([id, v]) => `<article class="check" id="${v.anchor}" data-id="${id}">
<h4><a class="self" href="#${v.anchor}" aria-label="link to this check">¶</a> ${esc(v.name)} <span class="status ${v.status.startsWith('pass') ? 'ok' : 'bad'}">${esc(v.status)}</span></h4>
<p>${rich(v.text)}</p><p class="measured">${rich(v.measured)}</p>${v.criterion ? `<p class="muted">Criterion: ${rich(v.criterion)}</p>` : ''}<p class="meta">id ${esc(id)}</p>
<p class="muted">${v.report ? `Measured values: <a href="validation/${v.anchor}.json">report (JSON)</a>` : `Measured values: <code>${esc(v.report_path)}</code> in ${repo('the source repository')}`}</p></article>`).join('\n');
  const refRows = Object.entries(R).filter(([, r]) => used.some(([, e]) => e.sources.some(x => R[x.ref] === r))).sort((a, b) => a[1].short.localeCompare(b[1].short)).map(([id, r]) =>
    `<li id="${r.anchor}" data-id="${id}"><span class="short">${esc(r.short)}.</span> ${esc(r.citation)}${r.links.length ? ` <span class="links">${refLinks(r)}</span>` : ''}</li>`).join('\n');
  const scenes = Object.values(beats).map(b => `<li>${scene(b.n)} — ${b.entries.map(x => `<a href="#${x.anchor}">${esc(x.title)}</a>`).join(' · ')}</li>`).join('\n');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Science notes · Lyα: from gas to forest</title>
<meta name="description" content="Sources, assumptions, teaching simplifications and numerical checks for every scientific claim in Lyα: from gas to forest.">
<style>
/* Embedded third-party assets: Fraunces, Inter (SIL OFL 1.1), IBM Plex Mono (SIL OFL 1.1, Reserved Font Name "Plex", unmodified), KaTeX and its fonts (MIT). Licence texts: ../licenses/ (THIRD_PARTY_LICENSES.md). */
${fontsCSS}
</style>
<style>
${katexCSS}
</style>
<style>
  :root { --paper:#FCFBF8; --ink:#1F2732; --graphite:#59616C; --muted:#6F7278; --hair:#D9D6CF; --accent:#B93A20; }
  html { background: var(--paper); } body { margin: 0 auto; max-width: 860px; padding: 40px 28px 80px; color: var(--ink); font: 300 15.5px/1.5 'Inter', sans-serif; }
  h1, h2, h3, h4 { font-family: 'Fraunces', serif; font-weight: 300; } h1 { font-size: 34px; margin: 6px 0 4px; } h2 { font-size: 25px; margin: 46px 0 10px; border-top: 1px solid var(--hair); padding-top: 18px; } h3 { font-size: 21px; margin: 34px 0 4px; } h4 { font-size: 19px; margin: 0 0 6px; } p.chap { margin: 0 0 6px; }
  a { color: var(--ink); text-decoration-color: var(--hair); text-underline-offset: 2px; } a:hover { text-decoration-color: var(--accent); } a.self { color: var(--muted); text-decoration: none; font-size: 15px; }
  .top { font: 400 11px 'IBM Plex Mono', monospace; color: var(--muted); letter-spacing: .04em; display: flex; justify-content: space-between; }
  .lede, .claim { font: 300 17px/1.5 'Fraunces', serif; } .muted { color: var(--muted); font-size: 13.5px; } .loc, code { font: 400 12px 'IBM Plex Mono', monospace; color: var(--graphite); overflow-wrap: anywhere; }
  .entry, .check { margin: 26px 0; padding-top: 4px; } .entry:target, .check:target, li:target { background: #F6F1E7; outline: 8px solid #F6F1E7; }
  dl.kv { display: grid; grid-template-columns: 150px 1fr; gap: 2px 14px; margin: 6px 0; font-size: 14px; } dl.kv dt { color: var(--muted); } dl.kv dd { margin: 0; } dl.kv ul { margin: 0; padding-left: 16px; }
  .eq { margin: 6px 0 8px; overflow-x: auto; } .eq .katex-display { margin: 4px 0; text-align: left; } .eq .katex-display > .katex { text-align: left; }
  .meta { font: 400 11px 'IBM Plex Mono', monospace; color: var(--muted); } .meta a { color: var(--muted); }
  .status { font: 400 11px 'IBM Plex Mono', monospace; } .status.ok { color: var(--graphite); } .status.bad { color: var(--accent); }
  .measured { font: 400 12px/1.5 'IBM Plex Mono', monospace; color: var(--graphite); }
  ol.refs, ul.plain { padding-left: 18px; } ol.refs li { margin: 6px 0; font-size: 14px; } .short { font-family: 'Fraunces', serif; } .links { font: 400 11.5px 'IBM Plex Mono', monospace; white-space: nowrap; }
  dl.terms dt { font-family: 'Fraunces', serif; font-size: 17px; margin-top: 10px; } dl.terms dd { margin: 2px 0 0; }
  nav.toc a { margin-right: 14px; } :focus-visible { outline: 1px dotted var(--graphite); outline-offset: 3px; }
  @media (max-width: 640px) { dl.kv { grid-template-columns: 1fr; } body { padding: 24px 16px 60px; } }
</style></head><body>
<div class="top"><a href="../lya.html">← the app</a><span>v${esc(version)}</span></div>
<h1>Science notes</h1>
<p class="lede">${rich(site.about)}</p>
<nav class="toc" aria-label="contents"><a href="#modeled">what is modeled</a><a href="#not-modeled">what is not</a><a href="#toy-and-real">toy and real</a><a href="#claims">the claims, in six chapters</a><a href="#accuracy">7 · validation and accuracy</a><a href="#scenes">by scene</a><a href="#references">references</a><a href="#cite">cite</a></nav>
<h2 id="modeled">What is modeled</h2><ul class="plain">${site.modeled.map(x => `<li>${rich(x)}</li>`).join('')}</ul>
<h2 id="not-modeled">What the teaching app does not model</h2><ul class="plain">${site.not_modeled.map(x => `<li>${rich(x)}</li>`).join('')}</ul>
<h2 id="toy-and-real">Toy, oracles and data</h2><dl class="terms">${site.toy_vs_real.map(x => `<dt>${esc(x.term)}</dt><dd>${rich(x.text)}</dd>`).join('')}</dl>
<h2 id="claims">The claims, in six chapters</h2>
<p class="muted">Each claim states what the app teaches, its sources at their exact location, its assumptions and validity, the simplifications made for teaching, and how its numbers are checked. Read in order, the chapters follow the story of the app: one atom, one line, the expanding universe, many contributions, the gas itself, and the inverse problem.</p>
${site.chapters.map(c => { const list = used.filter(([, e]) => c.domains.includes(e.domain)); return list.length ? `<section><h3 id="${c.anchor}">${esc(c.title)}</h3><p class="chap muted">${rich(c.intro)}</p>${list.map(entryCard).join('\n')}</section>` : ''; }).join('\n')}
<h2 id="accuracy">7 · Validation and numerical accuracy</h2>
<p class="muted">Each check is an automated test in ${repo('the source repository')}; its measured values are written by the test, never typed. Status: ${Object.entries(site.statuses).map(([k, v]) => `<b>${esc(k)}</b> — ${esc(v)}`).join('; ')}.</p>
${valRows}
<h2 id="scenes">Claims by scene</h2><ul class="plain">${scenes}</ul>
<h2 id="references">References</h2><ol class="refs">${refRows}</ol>
<h2 id="cite">Cite and version</h2>
<p>Lyα: from gas to forest — science notes, version ${esc(version)}. How to cite: see <code>CITATION.cff</code> in ${repo('the source repository')}. Fonts and KaTeX are redistributed under their own licences: <a href="../licenses/THIRD_PARTY_LICENSES.md">third-party licences</a>.</p>
</body></html>
`;
}
