#!/usr/bin/env python3
"""The data-release record: every data file in the repository, with its kind (synthetic / toy / derived from synthetic
inputs / validation output), creator, source, licence, whether it was modified, format, size and provenance. Writes
docs/DATA.md. Exit status 1 if a data file is not classified here, so nothing ships without a record.
Usage: python3 tools/data_inventory.py [--check]   (--check: verify docs/DATA.md and docs/DATA.sha256 are current, do not write)
The full SHA-256 of every data file is in docs/DATA.sha256: from the repository root, `shasum -a 256 -c docs/DATA.sha256`.
"""
import fnmatch, hashlib, json, os, subprocess, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
_rel = json.load(open(os.path.join(ROOT, 'release.json')))
_lic = (_rel.get('licences') or {}).get('data')
OWN = f'{_lic} (`LICENSE-DATA.md`)' if _lic else 'this project; the data licence is set at release (`release.json`)'
FREE = 'yes — generated by this project'
FREE_FS = 'yes — this project\'s outputs of MIT-licensed fake_spectra on synthetic inputs'
# (glob, kind, creator / source, licence, modified, provenance)
CLASSES = [
    ('science/data/toy/skewer.json', 'synthetic toy', 'this project — `science/data/toy/zeldovich3d.py` (seed 31415)', OWN, 'generated', 'one sightline through a 256³ Zel\'dovich-approximation volume (20 Mpc/h, z = 3, Planck 2018 parameters): x, Δ, T, v_pec, n_HI on 1024 pixels; the producer\'s own exact-Voigt τ for the reference view; the three teaching parcels'),
    ('science/data/toy/slab.json', 'synthetic toy', 'this project — `science/data/toy/zeldovich3d.py`', OWN, 'generated', 'log-density of a 20 × 8 × 8 Mpc/h block around the sightline (uint8), for the 3D view'),
    ('science/validation/voigt/oracle_grid.json', 'numerical oracle output', 'this project — `science/oracle/voigt_oracle.py` (SciPy `wofz`)', OWN, 'generated', 'H(a, x) on a 42 × 321 grid'),
    ('science/validation/tau/oracle.json', 'numerical oracle output', 'this project — `science/oracle/tau_oracle.py`', OWN, 'generated', 'exact-Voigt optical depths of controlled test lines'),
    ('science/validation/mapping/oracle.json', 'numerical oracle output', 'this project — `science/oracle/mapping_oracle.py`', OWN, 'generated', 'independent real-to-velocity maps and exact distance–redshift values'),
    ('science/validation/redshift/oracle.json', 'numerical oracle output', 'this project — `science/oracle/redshift_oracle.py` (SciPy integration)', OWN, 'generated', 'comoving distances and their inverse'),
    ('science/validation/degeneracy/oracle.json', 'numerical oracle output', 'this project — `science/oracle/degeneracy_oracle.py`', OWN, 'generated', 'exact-Voigt spectra and Δχ² of the "same shadow" configurations'),
    ('science/validation/degeneracy/configs.json', 'synthetic teaching configurations', 'this project', OWN, 'authored', 'the three gas configurations of the "same shadow" scene'),
    ('science/validation/closure/cases/*.json', 'derived from synthetic inputs', 'this project — `science/oracle/fakespectra_closure.py`, running fake_spectra 2.2.4 (S. Bird, MIT) on controlled synthetic skewers', OWN + '; produced with MIT-licensed fake_spectra', 'generated', 'per-case optical depths and flux from fake_spectra, the browser method and an exact reference'),
    ('science/validation/closure/metrics.json', 'derived from synthetic inputs', 'this project — closure study', OWN, 'generated', 'the closure metrics over all cases'),
    ('science/validation/closure/validation_mode.json', 'derived from synthetic inputs', 'this project — `science/oracle/fakespectra_validation_mode.py`', OWN, 'generated', 'the convention-aligned closure check'),
    ('science/validation/closure/mocksnap.json', 'derived from synthetic inputs', 'this project — `science/oracle/fakespectra_mocksnap.py` (a 3-particle mock snapshot)', OWN, 'generated', 'fake_spectra unit-convention checks'),
    ('science/validation/closure/js_vs_port.json', 'validation output', 'this project', OWN, 'generated', 'browser JavaScript vs its Python port'),
    ('science/validation/*/report.json', 'validation output', 'this project — `science/tests/` (and `app/smoke.mjs` for render)', OWN, 'generated', 'measured results of each validation; read by the build, never typed'),
]
DATA_EXT = ('.json', '.csv', '.npz', '.npy', '.bin', '.hdf5', '.h5', '.fits', '.dat', '.txt')
DATA_DIRS = ('science/data/', 'science/validation/')

def tracked():
    r = subprocess.run(['git', 'ls-files', '-z'], cwd=ROOT, capture_output=True)
    return [f for f in r.stdout.decode().split('\0') if f]

def main():
    files = sorted(f for f in tracked() if f.startswith(DATA_DIRS) and f.endswith(DATA_EXT))
    rows, missing = [], []
    for f in files:
        c = next((c for c in CLASSES if fnmatch.fnmatch(f, c[0])), None)
        if not c: missing.append(f); continue
        size = os.path.getsize(os.path.join(ROOT, f)); sha = hashlib.sha256(open(os.path.join(ROOT, f), 'rb').read()).hexdigest()
        rows.append((f, c, size, sha))
    L = ['# Data in this repository', '', '*Generated by `python3 tools/data_inventory.py`; every data file must be classified there, or the check fails.*', '',
         'Everything here is **synthetic** or **derived from synthetic inputs**, made by this project. No survey data and no data from any simulation suite are included.',
         'The toy volume is a Zel\'dovich-approximation stand-in, not a hydrodynamic simulation.',
         'Validation outputs are written by the tests and read by the build: they are never typed by hand.',
         'Nothing here is restricted: every file may be redistributed (column "redistributable"). The table shows the first 16 hex digits of each SHA-256; the full digests are in `docs/DATA.sha256` (from the repository root: `shasum -a 256 -c docs/DATA.sha256`).', '',
         f'{len(rows)} files, {sum(r[2] for r in rows) / 1e6:.1f} MB.', '',
         '| file | kind | creator / source | licence | redistributable | modified | format | size | sha256 | provenance |', '|---|---|---|---|---|---|---|---|---|---|']
    for f, c, size, sha in rows:
        L.append(f'| `{f}` | {c[1]} | {c[2]} | {c[3]} | {FREE_FS if "fake_spectra" in c[2] else FREE} | {c[4]} | {os.path.splitext(f)[1][1:].upper()} | {size / 1e3:.1f} kB | `{sha[:16]}` | {c[5]} |')
    L += ['', 'Code that produces data (`science/data/toy/zeldovich3d.py`, `science/oracle/*.py`) is part of the source and is covered by the code licence.', '']
    text = '\n'.join(L)
    sums = ''.join(f'{sha}  {f}\n' for f, c, size, sha in rows)   # shasum / sha256sum format
    if missing:
        print('UNCLASSIFIED data files:'); [print('  ' + m) for m in missing]; sys.exit(1)
    out, out2 = os.path.join(ROOT, 'docs/DATA.md'), os.path.join(ROOT, 'docs/DATA.sha256')
    if '--check' in sys.argv:
        for o, want in ((out, text), (out2, sums)):
            cur = open(o).read() if os.path.exists(o) else ''
            if cur != want: print(f'{os.path.relpath(o, ROOT)} is not current: run python3 tools/data_inventory.py'); sys.exit(1)
        print(f'data inventory: {len(rows)} files classified; docs/DATA.md and docs/DATA.sha256 are current'); return
    os.makedirs(os.path.dirname(out), exist_ok=True); open(out, 'w').write(text); open(out2, 'w').write(sums)
    print(f'data inventory: {len(rows)} files classified → docs/DATA.md, docs/DATA.sha256')

if __name__ == '__main__': main()
