#!/usr/bin/env python3
"""Provenance check: for every beat, can an outside reader follow beat → claim → assumptions → source → exact location
→ validation, using only public material? Reads the generated design/canonical/public_provenance.json and the built
science page; writes a markdown table. Nothing here is typed by hand: every cell is counted from the generated files.

Usage: python3 tools/provenance_check.py OUT.md      (exit 1 if a hard criterion fails)
"""
import json, os, re, subprocess, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
P = lambda *a: os.path.join(ROOT, *a)
prov = json.load(open(P('design/canonical/public_provenance.json')))
notes = open(P('app/dist/science/index.html')).read()
sys.dont_write_bytecode = True; sys.path.insert(0, P("tools")); import export_public as X   # the public allowlist
tracked = subprocess.run(['git', 'ls-files'], cwd=ROOT, capture_output=True, text=True).stdout.split('\n')
public_files = {f for f in tracked if f and any(f == inc or (inc.endswith('/') and f.startswith(inc)) for inc in X.INCLUDE)}
E, R, V = prov['entries'], prov['references'], prov['validations']
by_anchor = {e['anchor']: (k, e) for k, e in E.items()}
ids_in_page = set(re.findall(r'\bid="([^"]+)"', notes))
fails, rows, chain = [], [], {}

def public_text(o):
    if isinstance(o, str): return [o]
    if isinstance(o, list): return [t for x in o for t in public_text(x)]
    if isinstance(o, dict): return [t for k, x in o.items() if k not in ('report_path',) for t in public_text(x)]
    return []

for n in map(str, range(14)):
    b = prov['beats'][n]
    ents = [by_anchor[x['anchor']] for x in b['entries'] if x['anchor'] in by_anchor]
    n_src = sum(1 for _, e in ents if e.get('sources'))
    n_basis = sum(1 for _, e in ents if not e.get('sources') and (e.get('basis') or e.get('representation')))
    unsourced = [k for k, e in ents if not e.get('sources') and not e.get('basis') and not e.get('representation')]
    n_ass = sum(1 for _, e in ents if e.get('assumptions'))
    locs = [s for _, e in ents for s in (e.get('sources') or [])]
    n_loc = sum(1 for s in locs if (s.get('location') or '').strip())
    vals = b.get('validations') or []
    bad_anchor = [x['anchor'] for x in b['entries'] if x['anchor'] not in ids_in_page]
    ok = bool(b.get('claim')) and bool(b.get('simplifications')) and not unsourced and not bad_anchor and n_loc == len(locs)
    if not ok: fails.append(f"beat {n}: claim={bool(b.get('claim'))} simplifications={bool(b.get('simplifications'))} unsourced={unsourced} anchors missing={bad_anchor} locations {n_loc}/{len(locs)}")
    rows.append(f"| {n} · {b['title']} | {'yes' if b.get('claim') else '**no**'} | {len(ents)} ({n_ass} with assumptions) | {len(b.get('simplifications') or [])} | {len(b.get('equations') or [])} | {n_src} cited, {n_basis} declared basis{', **' + ', '.join(unsourced) + ' unsourced**' if unsourced else ''} | {n_loc}/{len(locs)} | {', '.join(vals) or '—'} | {'all' if not bad_anchor else '**missing ' + ', '.join(bad_anchor) + '**'} |")
    chain[n] = (b, ents)

# the whole public layer: no "proposed" status, no unresolved placeholder, no path a public reader cannot open
alltext = '\n'.join(public_text(prov))
for pat, why in [(r'\(proposed', 'a validation or criterion is still "proposed"'), (r'\{\{(?:VAL|SCI)-', 'an unresolved placeholder'), (r'\bunverified\b', 'an unverified source')]:
    for m in re.finditer(pat, alltext): fails.append(f'{why}: …{alltext[max(0, m.start() - 60):m.end() + 40]}…')
paths = sorted(set(re.findall(r'\b((?:science|app|design|tools|docs)/[\w./-]+\.\w+)', alltext)))
private_paths = [p for p in paths if p not in public_files]
for p in private_paths: fails.append(f'public text names a path outside the public export: {p}')
statuses = sorted({e.get('status') for e in E.values()})

md = lambda t: re.sub(r'\[\[#([^|\]]+)\|([^\]]+)\]\]', r'[\2](#\1)', t)   # the ledger's [[#anchor|title]] links, as markdown
def trace(n):
    b, ents = chain[n]; out = [f"**Beat {n} · {b['title']}** — claim: {b['claim']}", '']
    for k, e in ents:
        src = e.get('sources') or []
        s = '; '.join(f"{R[x['ref']]['short']} — {x['location']}" for x in src[:2]) if src else f"no literature source — basis: {e.get('basis') or 'a teaching representation'}"
        val = ', '.join(e.get('validations') or []) or '—'
        out.append(md(f"- [{e['title']}](#{e['anchor']}) · assumptions: {'; '.join(e.get('assumptions') or []) or 'none stated'} · source: {s} · validation: {val} ({e.get('status')})"))
    return '\n'.join(out)

doc = ['# Provenance check — beat by beat', '',
       '*Generated by `tools/provenance_check.py` from `design/canonical/public_provenance.json` and the built science',
       'page. Counts only; nothing typed by hand.*', '',
       '| beat | public claim | entries (with assumptions) | simplifications | equations | sources | exact locations | validations | science-page anchors |',
       '|---|---|---|---|---|---|---|---|---|', *rows, '',
       f"- Entry statuses in use: {', '.join(statuses)}.",
       f"- Repository paths named in public text: {len(paths)}; outside the public export: {len(private_paths)}.",
       f"- Hard criteria (claim, simplifications, a source or declared basis for every entry, a location for every citation, every anchor on the science page; no \"proposed\", no placeholder, no unverified source, no private path): **{'all pass' if not fails else str(len(fails)) + ' failures'}**.", '']
for f in fails: doc.append(f'  - FAIL {f}')
doc += ['', '## Expert traces (beat → claim → assumptions → source → exact location → validation)', '']
for n in ('3', '5', '6', '12', '13'): doc += [trace(n), '']
open(sys.argv[1], 'w').write('\n'.join(doc) + '\n')
print(f"provenance check: 14 beats; {len(paths)} public paths ({len(private_paths)} private); {len(fails)} failures")
sys.exit(1 if fails else 0)
